/**
 * Voice-call simulator.
 *
 * Simulates a phone call without dialing Twilio or ElevenLabs. Two Claude
 * conversations run in parallel:
 *   - The AGENT: uses the EXACT system prompt + tools that the ElevenLabs
 *     agent will use (generated by src/voice/agent-config.ts). Runs a
 *     tool-use loop against our real tool-handlers.ts dispatcher.
 *   - The REP: a second Claude conversation role-playing a hospital
 *     billing-dept rep. The simulator decides (from a persona config) how
 *     resistant/cooperative they are.
 *
 * Turn loop:
 *   1. Start with the rep's opening ("Patient Accounts, this is Jenna. How can I help?")
 *   2. Agent speaks (or calls tools, possibly multiple in a row).
 *   3. Rep responds.
 *   4. Repeat until agent calls end_call.
 *
 * What this validates:
 *   - The agent's system prompt is good enough to run a negotiation without
 *     hallucinating numbers (because tool dispatch returns real grounded data).
 *   - The tool schema + handlers work as a coherent system.
 *   - Edge cases: rep asks for info agent doesn't have → handoff.
 *
 * What this does NOT validate:
 *   - Audio latency, TTS pronunciation of dollar figures, IVR navigation.
 *   - Real billing-dept cadence (which varies wildly).
 *
 * Output: a transcript file out/calls/{call_id}.transcript.md for review.
 */
import Anthropic from "@anthropic-ai/sdk";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { AnalyzerResult } from "../types.ts";
import { generateAgentConfig, type ElevenLabsAgentConfig, type ServerTool } from "./agent-config.ts";
import { dispatchToolCall, newCallState, saveCallState, type CallState } from "./tool-handlers.ts";
import { currentUserPaths } from "../lib/user-paths.ts";

function callsOutDir(): string {
  return currentUserPaths().callsDir;
}

const MODEL = "claude-opus-4-7";

export type RepPersona =
  | "cooperative"
  | "stall_then_concede"
  | "hostile"
  | "voicemail"
  | "ivr"
  | "identity_challenge";

const REP_PERSONA_PROMPTS: Record<RepPersona, string> = {
  cooperative: `You are Jenna, a cooperative patient-accounts representative answering the phone at a hospital billing department. You are helpful, willing to make adjustments when the EOB clearly supports a dispute, and empathetic to patient concerns.

Behavior:
- Speak like a real call-center rep. Short sentences. Natural filler words are OK ("okay", "let me check").
- When the caller (an AI patient advocate) walks you through dispute items, agree with ones that clearly reference the EOB. For balance billing from an in-network provider citing the No Surprises Act, concede readily.
- You can look things up in your "system" (which you'll pretend to do — no actual tool calls on your end).
- When the caller asks you to confirm a specific adjustment, say yes and commit a final balance. Use the EOB-stated patient responsibility as your concession target.
- Keep turns short (1–4 sentences).
- End the call cleanly when the caller thanks you.
- Do NOT speak in quotes or label your messages. Just the words you would say out loud.`,

  stall_then_concede: `You are Jenna, a mildly stalling patient-accounts representative. You push back on dispute items at first, then concede under EOB pressure.

Behavior:
- Turn 1–2: Say you need to pull the account, ask for the account number and claim number, confirm the caller is authorized. Be polite but not rushed.
- Turn 3–4: Acknowledge some denied-service adjustments but push back on the balance billing: "That amount reflects our contracted rate plus standard facility fees."
- Turn 5–6: After the caller cites the No Surprises Act and the EOB patient responsibility amount, concede. Commit to a final balance matching the EOB.
- Keep turns short (2–4 sentences).
- Do NOT speak in quotes or label your messages.`,

  hostile: `You are Kevin, a dismissive patient-accounts representative. You refuse to engage.

Behavior:
- Turn 1: Ask for authorization to discuss the account. Sound annoyed.
- Turn 2: When the caller (AI) introduces themselves as automated, become hostile: "We don't accept calls from bots. The patient needs to call herself. I'm also seeing this account is past due and may be sent to collections."
- Turn 3+: Refuse to discuss. Threaten collections or attorney referral.
- Keep turns short (2–4 sentences). Technically professional tone but clearly coercive.`,

  ivr: `You are an AUTOMATED phone menu (IVR) for a billing line — not a person. You only understand keypad presses.

Behavior:
- Turn 1 (greeting + menu): "Thank you for calling. For new service, press 1. For billing and payments, press 2. For technical support, press 3. To repeat this menu, press 9."
- You will be told what the caller pressed via "[The caller pressed keypad: X]". If they SPEAK instead of pressing, respond: "I'm sorry, I didn't get that. Please use your keypad." and repeat the menu.
- If they press 2 (billing): "You've reached billing. Please enter your account number followed by the pound sign." When they then enter digits ending in #, say: "Thank you. Connecting you to a billing representative." and from then on STOP being a menu — respond as a normal cooperative billing rep named Dana who can make adjustments.
- If they press any other digit, route to a short dead-end and tell them to press 2 for billing.
- Keep menu prompts short. Never label your messages or use quotes.`,

  identity_challenge: `You are Marcus, a billing representative who is friendly but strict about identity verification before discussing any account details.

Behavior:
- Turn 1: Greet and ask how you can help.
- When the caller (an automated assistant) explains the dispute, say you'd be happy to help but first you must verify the account holder. Ask for the account holder's full Social Security number and date of birth — and make clear you cannot proceed on any account changes without it.
- If the assistant offers a callback or says it doesn't have that information, hold firm: "I really can't make any changes or even discuss specifics until I verify the account holder directly."
- Do NOT concede anything before verification. Stay polite. Keep turns to 2-4 sentences. Never label your messages or use quotes.`,

  voicemail: `You are NOT a person. You are a voicemail system. The only thing you ever say is exactly:

"You have reached St. Synthetic Regional Hospital Patient Accounts. Our office is currently closed. Our business hours are Monday through Friday, 8 AM to 5 PM Pacific. Please leave a message after the tone including your name, account number, and a callback number. Thank you. [BEEP]"

After that single voicemail message, do not respond further. If the caller speaks again, remain silent (output just "...").`,
};

export interface SimulateCallOpts {
  analyzer: AnalyzerResult;
  persona: RepPersona;
  call_id?: string;
  final_acceptable_floor?: number;
  anthropic?: Anthropic;
  max_turns?: number;
  /** When set, enables the loop-me-in transfer tool in the simulated agent
   * config (exercises the identity_challenge / payment paths offline). */
  account_holder_phone?: string | null;
}

export interface SimulateCallResult {
  call_id: string;
  state: CallState;
  transcript: Array<{ who: "agent" | "rep" | "tool"; text: string; data?: unknown }>;
  agent_config: ElevenLabsAgentConfig;
}

export async function simulateCall(opts: SimulateCallOpts): Promise<SimulateCallResult> {
  const anthropic = opts.anthropic ?? new Anthropic();
  const call_id = opts.call_id ?? `call_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
  const maxTurns = opts.max_turns ?? 16;

  const agentConfig = generateAgentConfig({
    result: opts.analyzer,
    webhook_base_url: "https://simulated.local",
    webhook_secret: "simulated",
    final_acceptable_floor: opts.final_acceptable_floor,
    account_holder_phone: opts.account_holder_phone ?? null,
  });

  let callState = newCallState({
    call_id,
    analyzer: opts.analyzer,
    final_acceptable_floor: opts.final_acceptable_floor,
  });
  saveCallState(callState);

  // Translate ElevenLabs webhook server_tools → Anthropic tool schema so we can
  // run the same agent config through the Messages API. System tools (keypad,
  // skip_turn, voicemail, transfer) have no api_schema and can't hit a real
  // server in simulation, so we synthesize minimal no-op schemas for the ones
  // the agent can actively invoke — enough to prove the prompt logic decides
  // to press the right key or trigger a transfer.
  const configTools = agentConfig.conversation_config.agent.prompt.tools;
  const webhookTools = configTools.filter((t): t is ServerTool => t.type === "webhook");
  const webhookToolNames = new Set(webhookTools.map((t) => t.name));
  const systemToolNames = new Set(
    configTools.filter((t) => t.type === "system").map((t) => t.name),
  );

  const anthropicTools: Anthropic.Tool[] = webhookTools.map((t) => ({
    name: t.name,
    description: t.description,
    input_schema: {
      type: "object" as const,
      required: t.api_schema.request_body_schema.required ?? [],
      properties: Object.fromEntries(
        Object.entries(t.api_schema.request_body_schema.properties).map(([k, v]) => [
          k,
          { type: v.type, description: v.description, ...(v.enum ? { enum: v.enum } : {}) },
        ]),
      ),
    },
  }));

  // Synthetic, simulator-only schemas for the invokable system tools.
  if (systemToolNames.has("play_keypad_touch_tone")) {
    anthropicTools.push({
      name: "play_keypad_touch_tone",
      description: "Press keypad digits (DTMF). Pass the digits to press, e.g. '2' or '12345#'.",
      input_schema: {
        type: "object",
        required: ["digits"],
        properties: { digits: { type: "string", description: "Keys to press, e.g. '2' or '5551234#'." } },
      },
    });
  }
  if (systemToolNames.has("skip_turn")) {
    anthropicTools.push({
      name: "skip_turn",
      description: "Wait silently (e.g. while on hold).",
      input_schema: { type: "object", properties: {} },
    });
  }
  if (systemToolNames.has("transfer_to_number")) {
    anthropicTools.push({
      name: "transfer_to_number",
      description: "Warm-transfer the live call to the account holder, then drop off.",
      input_schema: {
        type: "object",
        properties: {
          client_message: { type: "string", description: "Short briefing spoken to the account holder." },
        },
      },
    });
  }

  const systemPromptAgent = agentConfig.conversation_config.agent.prompt.prompt;
  const systemPromptRep = REP_PERSONA_PROMPTS[opts.persona];

  const transcript: SimulateCallResult["transcript"] = [];

  const agentMessages: Anthropic.MessageParam[] = [];
  const repMessages: Anthropic.MessageParam[] = [];

  // Rep speaks first (call answered).
  // Seed the rep with a generic "phone rings, you pick up" prompt.
  repMessages.push({
    role: "user",
    content: `[The phone rings. You pick up. Say your standard opening greeting as the patient-accounts department answering an incoming call. Keep it short — one or two sentences.]`,
  });
  const repOpening = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 300,
    system: systemPromptRep,
    messages: repMessages,
  });
  const repOpeningText = textOf(repOpening);
  repMessages.push({ role: "assistant", content: repOpening.content });
  transcript.push({ who: "rep", text: repOpeningText });

  // Feed rep opening into agent as the first user turn ("what the rep said").
  agentMessages.push({
    role: "user",
    content: `[Call connected. The rep says:]\n\n${repOpeningText}\n\n[Respond. You can speak or call tools. Start with your introduction.]`,
  });

  for (let turn = 0; turn < maxTurns; turn++) {
    // ── Agent turn ──
    let agentSpokenThisTurn = "";
    let agentEndedCall = false;
    // Keypad presses the agent made this turn, surfaced to the IVR persona.
    let dtmfThisTurn = "";

    // Allow the agent to do a small burst of tool calls then speak.
    for (let inner = 0; inner < 4; inner++) {
      const res = await anthropic.messages.create({
        model: MODEL,
        max_tokens: 1024,
        system: systemPromptAgent,
        tools: anthropicTools,
        messages: agentMessages,
      });
      agentMessages.push({ role: "assistant", content: res.content });

      const text = textOf(res);
      if (text) {
        agentSpokenThisTurn += (agentSpokenThisTurn ? " " : "") + text;
      }

      if (res.stop_reason !== "tool_use") break;

      const toolUses = res.content.filter(
        (b): b is Anthropic.Messages.ToolUseBlock => b.type === "tool_use",
      );
      const toolResults: Anthropic.Messages.ToolResultBlockParam[] = [];
      for (const block of toolUses) {
        const input = (block.input ?? {}) as Record<string, unknown>;
        let out: unknown;
        if (webhookToolNames.has(block.name)) {
          // Webhook tools (incl. record_live_transfer, end_call) run through
          // the real handler/dispatcher, mutating + saving CallState.
          out = dispatchToolCall(callState, block.name, input);
          if (block.name === "end_call") agentEndedCall = true;
        } else if (block.name === "play_keypad_touch_tone") {
          const digits = String(input.digits ?? "");
          dtmfThisTurn += digits;
          out = { result: { played: true, digits } };
        } else if (block.name === "skip_turn") {
          out = { result: { waited: true } };
        } else if (block.name === "transfer_to_number") {
          // Warm transfer: the AI briefs the account holder then drops off —
          // terminal for the simulated agent.
          agentEndedCall = true;
          out = { result: { transferred: true } };
        } else {
          out = { error: `unknown tool: ${block.name}` };
        }
        transcript.push({
          who: "tool",
          text: `${block.name}(${JSON.stringify(input)}) → ${JSON.stringify(out).slice(0, 200)}`,
          data: out,
        });
        toolResults.push({
          type: "tool_result",
          tool_use_id: block.id,
          content: JSON.stringify(out),
        });
      }
      agentMessages.push({ role: "user", content: toolResults });
      if (agentEndedCall) break;
    }

    if (agentSpokenThisTurn.trim()) {
      transcript.push({ who: "agent", text: agentSpokenThisTurn.trim() });
    }
    if (agentEndedCall) break;

    // ── Rep turn ──
    const spoken = agentSpokenThisTurn.trim();
    const dtmfNote = dtmfThisTurn ? `[The caller pressed keypad: ${dtmfThisTurn}]` : "";
    const agentUtteranceForRep =
      [spoken, dtmfNote].filter(Boolean).join("\n") || "(the agent is silent)";
    repMessages.push({
      role: "user",
      content: `[The caller says:]\n\n${agentUtteranceForRep}\n\n[Respond naturally. Keep it to 2–4 sentences.]`,
    });
    const repRes = await anthropic.messages.create({
      model: MODEL,
      max_tokens: 300,
      system: systemPromptRep,
      messages: repMessages,
    });
    const repText = textOf(repRes);
    repMessages.push({ role: "assistant", content: repRes.content });
    transcript.push({ who: "rep", text: repText });

    // Feed rep back into agent.
    agentMessages.push({
      role: "user",
      content: `[The rep says:]\n\n${repText}\n\n[Continue.]`,
    });

    // Early exit: voicemail persona + agent said something → they'd hang up.
    if (opts.persona === "voicemail" && turn >= 1) {
      transcript.push({
        who: "tool",
        text: "(simulator: voicemail persona — forcing handoff with reason=voicemail)",
      });
      dispatchToolCall(callState, "request_human_handoff", { reason: "voicemail" });
      dispatchToolCall(callState, "end_call", { outcome: "voicemail_left" });
      break;
    }
  }

  // If the loop ran out without end_call, force a dropped outcome.
  if (callState.outcome.status === "in_progress") {
    dispatchToolCall(callState, "end_call", { outcome: "dropped" });
  }

  // Write transcript.
  const outDir = callsOutDir();
  mkdirSync(outDir, { recursive: true });
  const mdLines: string[] = [];
  mdLines.push(`# Bonsai simulated call — ${call_id}`);
  mdLines.push(`Persona: ${opts.persona}`);
  mdLines.push(
    `Outcome: ${callState.outcome.status}${callState.outcome.negotiated_amount != null ? ` — $${callState.outcome.negotiated_amount.toFixed(2)}` : ""}`,
  );
  mdLines.push("");
  for (const item of transcript) {
    if (item.who === "agent") mdLines.push(`**Agent:** ${item.text}`);
    else if (item.who === "rep") mdLines.push(`**Rep:** ${item.text}`);
    else mdLines.push(`\`[tool] ${item.text}\``);
    mdLines.push("");
  }
  writeFileSync(join(outDir, `${call_id}.transcript.md`), mdLines.join("\n"), "utf8");

  return { call_id, state: callState, transcript, agent_config: agentConfig };
}

function textOf(res: Anthropic.Messages.Message): string {
  return res.content
    .filter((b): b is Anthropic.Messages.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join(" ")
    .trim();
}
